name: my action
runs:
 using: composite
 steps: 
 - run: echo "from composite action"
   shell: bash
   
 - run: echo "from composite action"
   shell: bash
   
 - run: echo "from composite action"
   shell: bash
