name: Delete Workflows

on: [workflow_dispatch]

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@c1a2f0de3fa4134a2357de83c92acff6e298bb8a # v2.0.3
        with:
          retain_days: 0
          keep_minimum_runs: 0
          
