name: GitHub Actions Demo

on: 
  push:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Secret value: ${{ secrets.DEMO_EXAMPLE }}"
        echo "Secret value: ${{ vars.DEMO_EXAMPLE }}"

  job-2:
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - run: |
        echo "Secret value: ${{ secrets.DEMO_EXAMPLE }}"
        echo "Secret value: ${{ vars.DEMO_EXAMPLE }}"

   
