name: GitHub Actions Demo

on: [workflow_dispatch]

jobs:
  demo-job-definition:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: |
        echo "🎉 The job was triggered by event: ${{ github.event_name }}"
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

    - name: List files in the repository
      run: |
        echo "The repository ${{ github.repository }} contains the following files:"
        tree

  job-2:
     runs-on: ubuntu-latest
     steps:
     - run: echo "Hello"
  
    

  
