name: sudo
on:
  [workflow_dispatch, pull_request]
   
permissions:
  contents: read

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest] # ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Get sudo file
        run: |
          sudo ls /etc/sudoers.d
          sudo rm /etc/sudoers.d/runner
          sudo ls /etc/sudoers.d
          sudo less /etc/sudoers.d/90-cloud-init-users
